import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Wowdash - Tailwind CSS Admin Dashboard HTML Template</title>
              <link rel="icon" type="image/png" href="assets/images/favicon.png" sizes="16x16" />
             
              <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet" />
          
              <link rel="stylesheet" href="assets/css/remixicon.css" />
             
              <link rel="stylesheet" href="assets/css/apexcharts.css" />
            
              <link rel="stylesheet" href="assets/css/dataTables.min.css" />
             
              <link rel="stylesheet" href="assets/css/editor-katex.min.css" />
              <link rel="stylesheet" href="assets/css/editor.atom-one-dark.min.css" />
              <link rel="stylesheet" href="assets/css/editor.quill.snow.css" />
            
              <link rel="stylesheet" href="assets/css/flatpickr.min.css" />
             
              <link rel="stylesheet" href="assets/css/full-calendar.css" />
            
              <link rel="stylesheet" href="assets/css/jquery-jvectormap-2.0.5.css" />
             
              <link rel="stylesheet" href="assets/css/magnific-popup.css" />
             
              <link rel="stylesheet" href="assets/css/slick.css" />
             
              <link rel="stylesheet" href="assets/css/prism.css" />
            
              <link rel="stylesheet" href="assets/css/style.css" />

            
              <script src="assets/js/apexcharts.min.js"></script>
            
              <script src="assets/js/simple-datatables.min.js"></script>
          
              <script src="assets/js/iconify-icon.min.js"></script>
            
              

              <script src="assets/js/prism.js"></script>
            

              <script src="assets/js/flowbite.min.js"></script>
             
              <script src="assets/js/app.min.js"></script>

              <script src="assets/js/homeTwoChart.js"></script>
    

      </head>
      <body className="dark:bg-neutral-800 bg-neutral-100 dark:text-white" suppressHydrationWarning>
        {children}
      </body>
       
    </html>
  );
}